name = "medistock"
main = "workers/medicine-api/src/index.ts"
compatibility_date = "2025-06-07"
compatibility_flags = ["global_fetch_strictly_public"]
node_compat = true

[env.production]
name = "react-medistock-prod"

[env.staging]
name = "react-medistock-staging"

[[d1_databases]]
binding = "DB"
database_name = "medicine-db"
database_id = "ea0c9e45-ba2d-41c4-9c73-8ecd1aa631d3"

[assets]
directory = "./frontend/dist"


[observability]
enabled = true

[vars]
NODE_ENV = "production"

# Secrets should be set using: wrangler secret put <SECRET_NAME>
# Example: wrangler secret put JWT_SECRET